name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python 3.10
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          check-latest: true
          update-environment: true

      # Step 3: Build with Buildozer inside the Docker image
      - name: Build with Buildozer
        uses: addnab/docker-run-action@v3
        with:
          image: kivy/buildozer:latest
          options: -v ${{ github.workspace }}:/app
          run: |
            echo "🚀 Starting Buildozer build for Caesar Cipher..."
            cd /app

            # Allow Buildozer to run as root
            export BUILDOZER_ALLOW_ROOT=1

            # Disable pip --user installs in virtualenv
            export PIP_USER=0

            # Install requirements if needed
            pip install --upgrade pip

            # Build the APK
            buildozer android debug
