name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Python (host, optional, mostly for pre-checks)
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          check-latest: false
          update-environment: true

      # 3️⃣ Build with Buildozer inside Docker
      - name: Build with Buildozer
        uses: addnab/docker-run-action@v3
        with:
          image: kivy/buildozer:latest
          options: -v ${{ github.workspace }}:/app
          run: |
            echo "🚀 Starting Buildozer build for Caesar Cipher..."
            cd /app

            # Allow running Buildozer as root
            export BUILDOZER_ALLOW_ROOT=1

            # Prevent pip from using --user inside virtualenv
            export PIP_USER=0
            export PIP_NO_USER_CONFIG=1
            export PIP_CONFIG_FILE=/dev/null

            # Upgrade pip, setuptools, and wheel globally
            python3 -m pip install --upgrade pip setuptools wheel

            # Optional: Upgrade Cython globally if needed
            python3 -m pip install --upgrade cython

            # Run Buildozer
            buildozer android debug
